### ISSUE TITLE
Deprecate

### ISSUE THREAD

**Issue by kentcdodds** [dualcyclone/gulp-filter-by#1]
If I'm not mistaken, @sindresorhus made [`gulp-filter`](https://github.com/sindresorhus/gulp-filter) [accept a function](https://github.com/sindresorhus/gulp-filter/blob/master/index.js#L11) that gets [passed the file](https://github.com/sindresorhus/gulp-filter/blob/master/index.js#L17), so I believe that it should be able to do this as well. Am I missing something that this does that `gulp-filter` does not?

**Comment by dualcyclone** [comment]
@sindresorhus - is it possible to update your API to make reference on how this would work in your plugin?

I wrote this one because I couldn't find a lightweight plugin that would allow me to write a custom filter. But looking at the logic it seems that this is indeed a duplicate.

**Comment by sindresorhus** [comment]
> is it possible to update your API to make reference on how this would work in your plugin?

Already there: https://github.com/sindresorhus/gulp-filter#pattern

**Comment by sindresorhus** [comment]
ping

**Comment by dualcyclone** [comment]
This issue has been fixed by the blacklisting referenced previously
